version: "3.8"
services:
############### RabbitMq ####################
        rabbitmq:
            image: rabbitmq:3.11-management
            container_name: rabbitmq
            hostname: rabbitmq
            ports:
              - "5672:5672"
              - "15672:15672"
            environment:
              - RABBITMQ_DEFAULT_USER=rabbituser
              - RABBITMQ_DEFAULT_PASS=rabbitpass
              - RABBITMQ_DEFAULT_VHOST=rabbitHost
            volumes:
              - ./rabbit/data:/var/lib/rabbitmq
              - ./rabbit/log:/var/log/rabbitmq
              - ./rabbit/etc:/etc/rabbitmq
            restart: always
###########Backend-Server###############
        tfg-app:
            container_name: tfg-app
            restart: always
            build: .
            ports:
              - ${PORT}:${PORT}
            links:
              - rabbitmq
              - mongo
              - mysql
            depends_on:
              - rabbitmq
              - mongo
              - mysql
            volumes:
              - .:/usr/src/app
############Databases################## 
        mongo:
              container_name: mongo
              image: mongo
              volumes:
                - ./mongodata:/data/db
              ports:
                - '27018:27017'
        mysql:
          image: mysql:8.0.32
          container_name: mysql
          volumes:
            - ./init:/docker-entrypoint-initdb.d
            - ./data/mysql:/var/lib/mysql
          ports:
            - "3306:3306"
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: root@123
            MYSQL_DATABASE: tfg
            TZ: "Asia/Kolkata"